export type SettingsSheetTarget =
  | "SettingsEnvironments"
  | "SettingsArchive"
  | "SettingsAppearance"
  | "SettingsProjectGrouping"
  | "SettingsClientStorage"
  | "SettingsUsage"
  | "SettingsByok"
  | "SettingsProviders"
  | "SettingsServer"
  | "SettingsIdeSessions"
  | "SettingsRuntimeDrivers"
  | "SettingsKeybindings"
  | "SettingsSourceControl"
  | "SettingsMcp"
  | "SettingsWorkspaceScripts"
  | "SettingsAutomations"
  | "SettingsDiagnostics"
  | "SettingsControlCenter"
  | "SettingsSquadExecutionHistory"
  | "SettingsSquadBuilder"
  | "SettingsTaskGraph"
  | "SettingsTeamRuntime"
  | "SettingsSupplierRegistry";

export type SettingsLegalDocumentTarget = "SettingsLegal";
