import type { MulticaRuntimeDraftIssueCode } from "./MulticaRuntimeSettings.model";
import { t } from "~/i18n";

export type MulticaRuntimeSettingsTextKey =
  | "title"
  | "add"
  | "loadingTitle"
  | "loadingDescription"
  | "loadFailedTitle"
  | "loadFailedDescription"
  | "retry"
  | "emptyTitle"
  | "emptyDescription"
  | "invalidSavedTitle"
  | "invalidSavedDescription"
  | "enabled"
  | "disabled"
  | "edit"
  | "delete"
  | "deleteConfirmTitle"
  | "deleteConfirmDescription"
  | "deleteFailed"
  | "createTitle"
  | "editTitle"
  | "unsavedChanges"
  | "saveFailed"
  | "saveConflict"
  | "cancel"
  | "save"
  | "saving"
  | "connectionSection"
  | "credentialsSection"
  | "routingSection"
  | "capabilitiesSection"
  | "executionSection"
  | "instanceId"
  | "runtimeId"
  | "daemonId"
  | "daemonRuntimeId"
  | "baseUrl"
  | "version"
  | "enableRuntime"
  | "headers"
  | "addHeader"
  | "emptyHeaders"
  | "headerName"
  | "environmentVariable"
  | "removeHeader"
  | "environment"
  | "addEnvironment"
  | "emptyEnvironment"
  | "variableName"
  | "variableValue"
  | "savedSecretPlaceholder"
  | "sensitive"
  | "removeEnvironment"
  | "addRoute"
  | "emptyRoutes"
  | "codeworkAgentId"
  | "codeworkSquadId"
  | "workspaceId"
  | "multicaAgentId"
  | "multicaSquadId"
  | "mcpCredentialEnvironmentVariable"
  | "removeRoute"
  | "capabilityList"
  | "addCapability"
  | "emptyCapabilities"
  | "capability"
  | "removeCapability"
  | "supportsResume"
  | "supportsMcp"
  | "taskMcpEndpoint"
  | "supportsSquad"
  | "supportsLeader"
  | "supportsTaskGraph"
  | "extensionCommand"
  | "extensionArgument"
  | "addExtensionArgument"
  | "removeExtensionArgument"
  | "extensionCwd"
  | "extensionTimeoutMs"
  | `issue.${MulticaRuntimeDraftIssueCode}`;

export type MulticaRuntimeSettingsText = (key: MulticaRuntimeSettingsTextKey) => string;

/** 所有面板文案经由静态 t() 调用登记，供 i18n 扫描器校验双语目录。 */
export const multicaRuntimeText: MulticaRuntimeSettingsText = (key) => {
  const catalog: Record<MulticaRuntimeSettingsTextKey, string> = {
    title: t("multicaRuntime.title"), add: t("multicaRuntime.add"), loadingTitle: t("multicaRuntime.loadingTitle"), loadingDescription: t("multicaRuntime.loadingDescription"), loadFailedTitle: t("multicaRuntime.loadFailedTitle"), loadFailedDescription: t("multicaRuntime.loadFailedDescription"), retry: t("retry"), emptyTitle: t("multicaRuntime.emptyTitle"), emptyDescription: t("multicaRuntime.emptyDescription"), invalidSavedTitle: t("multicaRuntime.invalidSavedTitle"), invalidSavedDescription: t("multicaRuntime.invalidSavedDescription"), enabled: t("enabled"), disabled: t("disabled"), edit: t("edit"), delete: t("delete"), deleteConfirmTitle: t("multicaRuntime.deleteConfirmTitle"), deleteConfirmDescription: t("multicaRuntime.deleteConfirmDescription"), deleteFailed: t("multicaRuntime.deleteFailed"), createTitle: t("multicaRuntime.createTitle"), editTitle: t("multicaRuntime.editTitle"), unsavedChanges: t("multicaRuntime.unsavedChanges"), saveFailed: t("multicaRuntime.saveFailed"), saveConflict: t("multicaRuntime.saveConflict"), cancel: t("cancel"), save: t("save"), saving: t("saving"), connectionSection: t("multicaRuntime.connectionSection"), credentialsSection: t("multicaRuntime.credentialsSection"), routingSection: t("multicaRuntime.routingSection"), capabilitiesSection: t("multicaRuntime.capabilitiesSection"), executionSection: t("multicaRuntime.executionSection"), instanceId: t("multicaRuntime.instanceId"), runtimeId: t("multicaRuntime.runtimeId"), daemonId: t("multicaRuntime.daemonId"), daemonRuntimeId: t("multicaRuntime.daemonRuntimeId"), baseUrl: t("multicaRuntime.baseUrl"), version: t("version"), enableRuntime: t("multicaRuntime.enableRuntime"), headers: t("headers"), addHeader: t("multicaRuntime.addHeader"), emptyHeaders: t("multicaRuntime.emptyHeaders"), headerName: t("multicaRuntime.headerName"), environmentVariable: t("multicaRuntime.environmentVariable"), removeHeader: t("multicaRuntime.removeHeader"), environment: t("environment"), addEnvironment: t("multicaRuntime.addEnvironment"), emptyEnvironment: t("multicaRuntime.emptyEnvironment"), variableName: t("variableName"), variableValue: t("value"), savedSecretPlaceholder: t("multicaRuntime.savedSecretPlaceholder"), sensitive: t("sensitive"), removeEnvironment: t("multicaRuntime.removeEnvironment"), addRoute: t("multicaRuntime.addRoute"), emptyRoutes: t("multicaRuntime.emptyRoutes"), codeworkAgentId: t("multicaRuntime.codeworkAgentId"), codeworkSquadId: t("multicaRuntime.codeworkSquadId"), workspaceId: t("multicaRuntime.workspaceId"), multicaAgentId: t("multicaRuntime.multicaAgentId"), multicaSquadId: t("multicaRuntime.multicaSquadId"), mcpCredentialEnvironmentVariable: t("multicaRuntime.mcpCredentialEnvironmentVariable"), removeRoute: t("multicaRuntime.removeRoute"), capabilityList: t("multicaRuntime.capabilityList"), addCapability: t("multicaRuntime.addCapability"), emptyCapabilities: t("multicaRuntime.emptyCapabilities"), capability: t("multicaRuntime.capability"), removeCapability: t("multicaRuntime.removeCapability"), supportsResume: t("multicaRuntime.supportsResume"), supportsMcp: t("multicaRuntime.supportsMcp"), taskMcpEndpoint: t("multicaRuntime.taskMcpEndpoint"), supportsSquad: t("multicaRuntime.supportsSquad"), supportsLeader: t("multicaRuntime.supportsLeader"), supportsTaskGraph: t("multicaRuntime.supportsTaskGraph"), extensionCommand: t("multicaRuntime.extensionCommand"), extensionArgument: t("multicaRuntime.extensionArgument"), addExtensionArgument: t("multicaRuntime.addExtensionArgument"), removeExtensionArgument: t("multicaRuntime.removeExtensionArgument"), extensionCwd: t("multicaRuntime.extensionCwd"), extensionTimeoutMs: t("multicaRuntime.extensionTimeoutMs"),
    "issue.invalid_instance_id": t("multicaRuntime.issue.invalidInstanceId"), "issue.invalid_runtime_identity": t("multicaRuntime.issue.invalidRuntimeIdentity"), "issue.invalid_base_url": t("multicaRuntime.issue.invalidBaseUrl"), "issue.invalid_environment": t("multicaRuntime.issue.invalidEnvironment"), "issue.invalid_environment_secret": t("multicaRuntime.issue.invalidEnvironmentSecret"), "issue.invalid_header_binding": t("multicaRuntime.issue.invalidHeaderBinding"), "issue.invalid_assignee_route": t("multicaRuntime.issue.invalidAssigneeRoute"), "issue.invalid_task_mcp_endpoint": t("multicaRuntime.issue.invalidTaskMcpEndpoint"), "issue.invalid_task_execution_extension": t("multicaRuntime.issue.invalidTaskExecutionExtension"), "issue.invalid_config": t("multicaRuntime.issue.invalidConfig"),
  };
  return catalog[key];
};
