/**
 * i18n codemod — migrates string-source t() calls to stable message keys.
 *
 * Scans apps/web/src for `t("...")` / `t('...')` calls whose first argument
 * is a string literal. For each distinct English source string it derives a
 * frozen camelCase message id, rewrites the call site to `t("<id>")`, and
 * regenerates `apps/web/src/i18n/messages.ts` with the `en` catalog (id →
 * English source) and the `zh-CN` catalog (id → translation from the legacy
 * source-string dictionary when present).
 *
 * Dynamic first arguments (template literals, concatenations, identifiers)
 * are reported and left untouched.
 */
import * as NodeFS from "node:fs";
import * as NodePath from "node:path";

const ROOT = NodePath.join(import.meta.dirname, "..", "apps", "web", "src");
const LEGACY_ZH = NodePath.join(ROOT, "i18n", "zh-CN.ts");
const MESSAGES = NodePath.join(ROOT, "i18n", "messages.ts");

const legacyZhSource = NodeFS.readFileSync(LEGACY_ZH, "utf8");
const legacyZh = {};
{
  const re = /^\s*"((?:[^"\\]|\\.)*)":\s*"((?:[^"\\]|\\.)*)",?\s*$/gm;
  let m;
  while ((m = re.exec(legacyZhSource))) {
    legacyZh[JSON.parse(`"${m[1]}"`)] = JSON.parse(`"${m[2]}"`);
  }
}

function slugify(source) {
  const words = source
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/<[^>]+>/g, " ")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map((w, i) => (i === 0 ? w.toLowerCase() : w[0].toUpperCase() + w.slice(1).toLowerCase()));
  let key = words.join("").slice(0, 60);
  if (!key) key = "message";
  if (/^\d/.test(key)) key = `m${key}`;
  return key;
}

function listFiles(dir) {
  const out = [];
  for (const entry of NodeFS.readdirSync(dir)) {
    const p = NodePath.join(dir, entry);
    if (NodeFS.statSync(p).isDirectory()) {
      if (entry === "i18n") continue; // skip the i18n module itself
      out.push(...listFiles(p));
    } else if (/\.(tsx?|mts?)$/.test(entry)) {
      out.push(p);
    }
  }
  return out;
}

// Matches t("...") and t('...') where the argument contains no quotes of the
// same kind and no backslash escapes beyond \" and \'.
const CALL_RE = /\bt\((["'])((?:[^\\'"]|\\.)*)\1\)/g;

const entries = new Map(); // key -> english
const bySource = new Map(); // english -> key
const dynamicHits = [];
const changedFiles = [];

for (const file of listFiles(ROOT)) {
  const source = NodeFS.readFileSync(file, "utf8");
  if (!/\bt\(/.test(source)) continue;
  let changed = false;
  let flagged = false;
  // Flag dynamic first arguments: t(`...`), t("a" + b), t(name)
  const dynamicRe = /\bt\((?:`|["'][^"']*["']\s*\+|[A-Za-z_$][\w.$]*)/g;
  let dm;
  while ((dm = dynamicRe.exec(source))) {
    // skip plain string literals already matched by CALL_RE
    const rest = source.slice(dm.index);
    if (!CALL_RE.test(rest.slice(0, rest.indexOf(")") + 1 || undefined))) {
      dynamicHits.push(
        `${NodePath.relative(process.cwd(), file)}: ${source.slice(dm.index, dm.index + 60).split("\n")[0]}`,
      );
      flagged = true;
    }
    CALL_RE.lastIndex = 0;
  }

  const rewritten = source.replace(CALL_RE, (full, quote, raw) => {
    const english = JSON.parse(`"${raw.replace(/"/g, '\\"')}"`);
    let key = bySource.get(english);
    if (!key) {
      key = slugify(english);
      let n = 2;
      while (entries.has(key) && entries.get(key) !== english) key = `${key}${n++}`;
      bySource.set(english, key);
      entries.set(key, english);
    }
    changed = true;
    return `t("${key}")`;
  });
  if (changed) {
    writeFileSync(file, rewritten);
    changedFiles.push(NodePath.relative(process.cwd(), file));
  }
}

const lines = [];
lines.push("/**");
lines.push(" * Message catalogs for the i18n system (generated by scripts/i18n-codemod.mjs).");
lines.push(" *");
lines.push(" * Catalogs are keyed by stable message ids. Every message exists in `en`;");
lines.push(" * other locales fall back to English at runtime. Placeholders use {{name}};");
lines.push(" * pluralizable messages use `key_plural` selected via a `count` param.");
lines.push(" */");
lines.push("export const en: Record<string, string> = {");
for (const [key, english] of [...entries].sort(([a], [b]) => a.localeCompare(b))) {
  lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(english)},`);
}
lines.push("};");
lines.push("");
lines.push("export const zhCN: Record<string, string> = {");
for (const [key, english] of [...entries].sort(([a], [b]) => a.localeCompare(b))) {
  const zh = legacyZh[english];
  if (zh !== undefined) lines.push(`  ${JSON.stringify(key)}: ${JSON.stringify(zh)},`);
}
lines.push("};");
lines.push("");
NodeFS.writeFileSync(MESSAGES, lines.join("\n"));

console.log(`files changed: ${changedFiles.length}`);
console.log(
  `messages: ${entries.size} (zh-CN: ${[...entries].filter(([, e]) => legacyZh[e] !== undefined).length})`,
);
const missing = [...entries].filter(([, e]) => legacyZh[e] === undefined).map(([, e]) => e);
if (missing.length) console.log(`missing zh translations:\n  ${missing.join("\n  ")}`);
if (dynamicHits.length)
  console.log(`dynamic t() calls left untouched:\n  ${dynamicHits.join("\n  ")}`);
