import {
  MessageId,
  ProjectId,
  ProviderInstanceId,
  ThreadId,
  TurnId,
  type OrchestrationThread,
} from "@codework/contracts";

export const makeAgentThread = (
  overrides: Partial<OrchestrationThread> = {},
): OrchestrationThread => ({
  id: ThreadId.make("thread-agent-1"),
  projectId: ProjectId.make("project-1"),
  title: "修复 CLI",
  modelSelection: { instanceId: ProviderInstanceId.make("codex"), model: "gpt-5.6" },
  runtimeMode: "full-access",
  interactionMode: "default",
  branch: "codex/cli-agent-controls",
  worktreePath: "C:/repo",
  latestTurn: {
    turnId: TurnId.make("turn-1"),
    state: "running",
    requestedAt: "2026-08-30T00:00:00.000Z",
    startedAt: "2026-08-30T00:00:01.000Z",
    completedAt: null,
    assistantMessageId: null,
  },
  createdAt: "2026-08-30T00:00:00.000Z",
  updatedAt: "2026-08-30T00:00:01.000Z",
  archivedAt: null,
  settledOverride: null,
  settledAt: null,
  deletedAt: null,
  messages: [
    {
      id: MessageId.make("message-user-1"),
      role: "user",
      text: "检查 CLI",
      turnId: TurnId.make("turn-1"),
      streaming: false,
      createdAt: "2026-08-30T00:00:00.000Z",
      updatedAt: "2026-08-30T00:00:00.000Z",
    },
    {
      id: MessageId.make("message-assistant-1"),
      role: "assistant",
      text: "正在检查\u001b[31m失败点\u001b[0m\u0000",
      turnId: TurnId.make("turn-1"),
      streaming: true,
      createdAt: "2026-08-30T00:00:01.000Z",
      updatedAt: "2026-08-30T00:00:02.000Z",
    },
  ],
  proposedPlans: [],
  activities: [],
  checkpoints: [],
  session: {
    threadId: ThreadId.make("thread-agent-1"),
    status: "running",
    providerName: "codex",
    providerInstanceId: ProviderInstanceId.make("codex"),
    runtimeMode: "full-access",
    activeTurnId: TurnId.make("turn-1"),
    lastError: null,
    updatedAt: "2026-08-30T00:00:01.000Z",
  },
  ...overrides,
});
